from BombaCombustivel import BombaCombustivel

abastecimento1 = BombaCombustivel("gasolina", 5.82, 10)
abastecimento1.AbastecerPorValor(50)
abastecimento1.AbastecerPorLitro(1)
abastecimento1.AlterarValorCombustivel(5.90)
abastecimento1.AbastecerPorLitro(0.3)
abastecimento1.AlterarQuantidadeCombustivel(50)
abastecimento1.AbastecerPorValor(60)
abastecimento1.AlterarTipoCombustivel("etanol")
abastecimento1.AbastecerPorValor(30)
abastecimento1.AlterarValorCombustivel(5.57)
abastecimento1.AbastecerPorValor(70)
abastecimento1.AbastecerPorValor(30)
abastecimento1.AbastecerPorLitro(4.5)
abastecimento1.AbastecerPorValor(40)
abastecimento1.AbastecerPorLitro(5.11)
abastecimento1.AbastecerPorLitro(5.11)
abastecimento1.AlterarQuantidadeCombustivel(20)
abastecimento1.AbastecerPorLitro(5.11)
abastecimento1.AbastecerPorValor(70)
abastecimento1.AbastecerPorLitro(2.32)
abastecimento1.AbastecerPorLitro(2.32)